name: Check and realese neurionpy
# runs do release on main branch updated
# script checks for current package version and the latest tag on github
# if package version is newer it build, upload, tag and make a release page on github
# secrets PYPI_USERNAME and PYPI_PASSWORD are required!
on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches:
      - release/*
      - master
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: '3.9'
    - name: Run release script
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # required to make a release page
        GH_TOKEN: ${{ github.token }}
      run: |
        pip install tomli packaging poetry
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        python3 ./scripts/do-release.py